// This file will be generated by Supabase CLI
// For now, we'll use a placeholder type
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: 'admin' | 'facilitator' | 'participant'
          avatar_url: string | null
          bio: string | null
          learning_preferences: Json | null
          partner_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role?: 'admin' | 'facilitator' | 'participant'
          avatar_url?: string | null
          bio?: string | null
          learning_preferences?: Json | null
          partner_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: 'admin' | 'facilitator' | 'participant'
          avatar_url?: string | null
          bio?: string | null
          learning_preferences?: Json | null
          partner_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

